### ISSUE TITLE
Issues when data paths contain "space"

### ISSUE THREAD

**Issue by Palaryel** [StollD/NOST#2]
Symptoms (tested with NOST 0.4 and 0.5): Upon selecting the image to flash the path to the image field in the tool remains blank and the "Next" button remains disabled. A command prompt windows opens and closes quickly (presumably the command to extract the .qlz file)

Cause: the data path leading to the temporary folder contains a "space". In my particular case the user directory contains 2 words separated by a space (e.g. C:\Users\XXX YYY\AppData\Local\Temp\tmpZZZZ)

Confirmation: Created another user on the same PC, where the new username contained only one word, the application worked as expected without any errors, thus confirming the above.

Log entries (notes: edited out the exact path since it contains my first and last name /// unrelated note: as can be seen on the 2nd log entry the error log point to your exact path to the .cs files, including your name and names of your project files which might cause a privacy concern on your end):

PC #1 :
[14:58:50::814][02484]	[ADB]: [Recv] OKAY
[14:58:55::940][02484]	[ERROR DESCRIPTION]: Catch exception - Could not find a part of the path 'C:\Users\XXXX XXXXc\AppData\Local\Temp\tmp1B4'. (Form1.btnSelectedFw_Click)
[14:58:55::950][02484]	[ERROR DESCRIPTION]: at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.Directory.InternalGetFileDirectoryNames( String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
at System.IO.Directory.GetFiles(String path, String searchPattern)
at NOST.Patches.LoadFwImagePatch.Prefix(String& fwPath, Int64& __result)
at LoadFwImage_Patch1(Object fwPath, String product, Product& )
at PageControl.FwPageSelected.SelectProduct(String initPath, Product& product)
at MainForms.Form1.JudgeProduct(String imagePath, TextBox textBox)
at MainForms.Form1.btnSelectedFw_Click(Object sender, EventArgs e)

PC #2:
[15:58:33::671][13660]	[ERROR DESCRIPTION]: at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.Directory.InternalGetFileDirectoryNames( String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
at System.IO.Directory.GetFiles(String path, String searchPattern)
at NOST.Patches.LoadFwImagePatch.Prefix(String& fwPath, Int64& __result) in C:\Users\dorian\Downloads\NOST-master\src\NOST\Patches\LoadFwImagePatch.cs:line 68
at LoadFwImage_Patch1(Object fwPath, String product, Product& )
at PageControl.FwPageSelected.SelectProduct(String initPath, Product& product)
at MainForms.Form1.JudgeProduct(String imagePath, TextBox textBox)
at MainForms.Form1.btnSelectedFw_Click(Object sender, EventArgs e)
[15:58:56::820][13660]	[ERROR DESCRIPTION]: Catch exception - Could not find a part of the path 'C:\Users\XXXXX XXXXX\AppData\Local\Temp\tmp7AF'. (Form1.btnSelectedFw_Click)
[15:58:56::835][13660]	[ERROR DESCRIPTION]: at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.Directory.InternalGetFileDirectoryNames( String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
at System.IO.Directory.GetFiles(String path, String searchPattern)
at NOST.Patches.LoadFwImagePatch.Prefix(String& fwPath, Int64& __result) in C:\Users\dorian\Downloads\NOST-master\src\NOST\Patches\LoadFwImagePatch.cs:line 68
at LoadFwImage_Patch1(Object fwPath, String product, Product& )
at PageControl.FwPageSelected.SelectProduct(String initPath, Product& product)
at MainForms.Form1.JudgeProduct(String imagePath, TextBox textBox)
at MainForms.Form1.btnSelectedFw_Click(Object sender, EventArgs e)

Note: Already reported the issue in the [XDA thread](https://forum.xda-developers.com/showpost.php?p=78903906&postcount=63) but wanted to post here as well to raise awareness of the issue.

**Comment by StollD** [comment]
Could you try to download the attached zip file, and copy the .exe file thats inside into `C:\Program Files (x86)\NOST\OST`? It should replace one that already exists there (don't overwrite NOST.Launcher!).

It is a build of the latest commit I pushed to master which should hopefully fix your issue. Sadly I don't have a windows machine to test it right now, otherwise I would try it myself. :/

Also: Thanks for the debugging you already did, that helped me a lot figuring out what I missed!

[NOST-fix-for-spaces-in-filename.zip](https://github.com/StollD/NOST/files/2870731/NOST-fix-for-spaces-in-filename.zip)

**Comment by Palaryel** [comment]
Same symptoms. Error log:

[22:43:36::690][14348]	[COMMENT]: NOST v0.5
[22:43:36::697][14348]	[COMMENT]: Microsoft Windows 8 (build 9200), 64-bit
[22:43:36::704][14348]	[COMMENT]: 
[22:43:36::711][14348]	[COMMENT]: 
[22:43:36::826][14348]	[COMMENT]: Main form is loaded. (Form1.Form1_Load)
[22:43:40::958][14348]	[ERROR DESCRIPTION]: Catch exception - Could not find a part of the path 'C:\Users\XXXXX XXXXX\AppData\Local\Temp\tmpEF6B'. (Form1.btnSelectedFw_Click)
[22:43:40::968][14348]	[ERROR DESCRIPTION]:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at NOST.Patches.LoadFwImagePatch.Prefix(String& fwPath, Int64& __result)
   at LoadFwImage_Patch1(Object fwPath, String product, Product& )
   at PageControl.FwPageSelected.SelectProduct(String initPath, Product& product)
   at MainForms.Form1.JudgeProduct(String imagePath, TextBox textBox)
   at MainForms.Form1.btnSelectedFw_Click(Object sender, EventArgs e)

**Comment by StollD** [comment]
Could you try it again with this one? I literally forgot half of the fix I wanted to do. Sorry >.<

[NOST-fix-for-spaces-in-filename.zip](https://github.com/StollD/NOST/files/2871735/NOST-fix-for-spaces-in-filename.zip)

**Comment by Palaryel** [comment]
Yup, that did it, working as intended :D

**Comment by StollD** [comment]
I released v0.6 which contains this fix, so I am closing the issue.
